# Generated by Django 3.1.2 on 2021-02-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=100, verbose_name='收件人邮箱')),
            ],
            options={
                'verbose_name': '报告邮箱',
                'verbose_name_plural': '报告邮箱',
                'db_table': 'linerunner_meail',
            },
        ),
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('project_host', models.CharField(blank=True, choices=[['开发环境', '开发环境'], ['测试环境', '测试环境'], ['线上环境', '线上环境']], default=None, max_length=100, null=True, verbose_name='用例执行环境')),
                ('case_type', models.CharField(choices=[['ui', 'ui'], ['接口', '接口']], default=1, max_length=100, verbose_name='用例类型')),
                ('case_all', models.IntegerField(verbose_name='用例总数')),
                ('case_pass', models.IntegerField(verbose_name='用例成功次数')),
                ('case_fail', models.IntegerField(verbose_name='用例失败次数')),
                ('start_time', models.CharField(max_length=100, verbose_name='开始时间')),
                ('run_time', models.CharField(max_length=100, verbose_name='运行时间')),
                ('report_details', models.CharField(max_length=100, verbose_name='报告详情')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '报告表',
                'verbose_name_plural': '报告表',
                'db_table': 'linerunner_report',
                'ordering': ['-create_time'],
            },
        ),
    ]
