# Generated by Django 3.1.2 on 2021-02-25 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meail',
        ),
    ]
