# Generated by Django 3.1.2 on 2022-04-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_delete_meail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='report_details',
            field=models.CharField(max_length=300, verbose_name='报告详情'),
        ),
    ]
