# Generated by Django 3.1.2 on 2022-05-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20220426_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, verbose_name='邮箱地址')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('status', models.BooleanField(default=True, verbose_name='是否禁用')),
            ],
            options={
                'verbose_name': '邮箱表',
                'verbose_name_plural': '邮箱表',
                'db_table': 'linerunner_email',
            },
        ),
    ]
