# Generated by Django 3.1.2 on 2022-05-07 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='EmailModel',
        ),
    ]
