# Generated by Django 3.1.2 on 2021-02-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrontabTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('case_id', models.CharField(max_length=100, verbose_name='定时执行的用例')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('expr', models.CharField(max_length=200, verbose_name='任务执行表达式')),
                ('status', models.SmallIntegerField(choices=[(1, 1), (2, 2)], default=2, verbose_name='任务的状态')),
            ],
            options={
                'verbose_name': '定时任务',
                'verbose_name_plural': '定时任务',
                'db_table': 'fusion_crontab_task',
            },
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20, verbose_name='月份')),
                ('task_name', models.CharField(max_length=100, verbose_name='任务标题')),
                ('tester', models.CharField(max_length=50, null=True, verbose_name='测试人员')),
                ('develop', models.CharField(max_length=50, null=True, verbose_name='开发人员')),
                ('start_time', models.CharField(max_length=50, null=True, verbose_name='测试开始时间')),
                ('end_time', models.CharField(max_length=50, null=True, verbose_name='测试结束时间')),
                ('publish_time', models.CharField(max_length=200, null=True, verbose_name='发版时间')),
            ],
            options={
                'verbose_name': '测试任务表',
                'verbose_name_plural': '测试任务表',
                'db_table': 'fusion_test_task',
            },
        ),
    ]
