# Generated by Django 3.1.2 on 2021-03-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtask',
            name='end_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='测试结束时间'),
        ),
        migrations.AlterField(
            model_name='testtask',
            name='publish_time',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='发版时间'),
        ),
    ]
