# Generated by Django 3.1.2 on 2022-04-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20210408_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crontabtask',
            name='case_id',
            field=models.CharField(max_length=500, verbose_name='定时执行的用例'),
        ),
    ]
