# Generated by Django 3.1.2 on 2021-02-23 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChanDaoProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=30, verbose_name='项目名称')),
                ('product_person', models.CharField(max_length=10, verbose_name='产品负责人')),
                ('test_person', models.CharField(max_length=10, verbose_name='测试负责人')),
            ],
            options={
                'verbose_name': '阐道_项目名称',
                'verbose_name_plural': '阐道_项目名称',
                'db_table': 'fusion_chandao_project',
            },
        ),
        migrations.CreateModel(
            name='ChanDaoModular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modular', models.CharField(max_length=10, verbose_name='模块名称')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chanDao.chandaoproject')),
            ],
            options={
                'verbose_name': '阐道_项目模块',
                'verbose_name_plural': '阐道_项目模块',
                'db_table': 'fusion_chandao_modular',
            },
        ),
        migrations.CreateModel(
            name='ChanDaoCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='用例标题')),
                ('preconditions', models.CharField(max_length=200, verbose_name='前置条件')),
                ('case_step', models.CharField(max_length=3000, verbose_name='用例步骤')),
                ('case_type', models.CharField(choices=[['功能测试', '功能测试'], ['性能测试', '性能测试'], ['接口测试', '接口测试']], default='功能测试', max_length=10, verbose_name='用例类型')),
                ('case_stage', models.CharField(choices=[['功能测试阶段', '功能测试阶段'], ['系统测试阶段', '系统测试阶段'], ['冒烟测试阶段', '冒烟测试阶段']], default='功能测试阶段', max_length=10, verbose_name='适用阶段')),
                ('case_priority', models.IntegerField(choices=[['功能测试阶段', '功能测试阶段'], ['系统测试阶段', '系统测试阶段'], ['冒烟测试阶段', '冒烟测试阶段']], default=3, max_length=10, verbose_name='优先级')),
                ('remarks', models.CharField(max_length=3000, verbose_name='备注')),
                ('result', models.CharField(choices=[['pass', 'pass'], ['fail', 'fail'], ['block', 'block']], default='pass', max_length=3000, verbose_name='用例结果')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('found_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chanDao.chandaomodular')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '阐道_用例',
                'verbose_name_plural': '阐道_用例',
                'db_table': 'fusion_chandao_case',
            },
        ),
    ]
