# Generated by Django 3.1.2 on 2021-02-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chanDao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chandaocase',
            name='result',
            field=models.CharField(choices=[['unexecuted', 'unexecuted'], ['pass', 'pass'], ['fail', 'fail'], ['block', 'block']], default='unexecuted', max_length=3000, verbose_name='用例结果'),
        ),
    ]
