# Generated by Django 3.1.2 on 2021-02-24 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chanDao', '0003_chandaocasestep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chandaocase',
            name='case_step',
        ),
        migrations.AlterField(
            model_name='chandaocase',
            name='result',
            field=models.CharField(choices=[['unexecuted', 'unexecuted'], ['pass', 'pass'], ['fail', 'fail']], default='unexecuted', max_length=3000, verbose_name='用例结果'),
        ),
        migrations.AlterField(
            model_name='chandaocasestep',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case', to='chanDao.chandaocase'),
        ),
    ]
