# Generated by Django 3.1.2 on 2021-02-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chanDao', '0005_auto_20210224_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chandaocase',
            name='case_priority',
            field=models.IntegerField(choices=[[1, 1], [2, 2], [3, 3], [4, 4]], max_length=10, verbose_name='优先级'),
        ),
    ]
