# Generated by Django 3.1.2 on 2021-03-01 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chanDao', '0007_auto_20210225_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chandaocase',
            name='modular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chanDao.chandaomodular', verbose_name='模块'),
        ),
        migrations.AlterField(
            model_name='chandaocasestep',
            name='remarks',
            field=models.CharField(max_length=3000, null=True, verbose_name='备注'),
        ),
    ]
