# Generated by Django 3.1.2 on 2021-03-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chanDao', '0008_auto_20210301_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chandaocasestep',
            name='remarks',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='备注'),
        ),
    ]
