# Generated by Django 3.1.2 on 2021-04-08 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chanDao', '0009_auto_20210302_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chandaoproject',
            options={'ordering': ['id'], 'verbose_name': '阐道_项目名称', 'verbose_name_plural': '阐道_项目名称'},
        ),
    ]
