# Generated by Django 3.1.2 on 2022-04-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chanDao', '0010_auto_20210408_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chandaomodular',
            name='modular',
            field=models.CharField(max_length=20, verbose_name='模块名称'),
        ),
        migrations.AlterField(
            model_name='chandaoproject',
            name='product_person',
            field=models.CharField(max_length=20, verbose_name='产品负责人'),
        ),
        migrations.AlterField(
            model_name='chandaoproject',
            name='test_person',
            field=models.CharField(max_length=20, verbose_name='测试负责人'),
        ),
    ]
